FROM node:current-alpine as base

RUN apk add --no-cache libc6-compat

WORKDIR /app

ARG NEXT_PUBLIC_AWS_REGION
ARG NEXT_PUBLIC_AWS_ACCOUNT
ARG NEXT_PUBLIC_S3_BUCKET
ARG NEXT_PUBLIC_USER_POOL_ID
ARG NEXT_PUBLIC_USER_POOL_CLIENT_ID
ARG NEXT_PUBLIC_USER_POOL_IDENTITY_ID

ENV NEXT_PUBLIC_AWS_REGION=$NEXT_PUBLIC_AWS_REGION
ENV NEXT_PUBLIC_AWS_ACCOUNT=$NEXT_PUBLIC_AWS_ACCOUNT
ENV NEXT_PUBLIC_S3_BUCKET=$NEXT_PUBLIC_S3_BUCKET
ENV NEXT_PUBLIC_USER_POOL_ID=$NEXT_PUBLIC_USER_POOL_ID
ENV NEXT_PUBLIC_USER_POOL_CLIENT_ID=$NEXT_PUBLIC_USER_POOL_CLIENT_ID
ENV NEXT_PUBLIC_USER_POOL_IDENTITY_ID=$NEXT_PUBLIC_USER_POOL_IDENTITY_ID

COPY package.json .

RUN npm i

COPY . . 

WORKDIR /app/apps/next-app

RUN npm run build

FROM node:current-alpine as runtime

RUN apk add --no-cache libc6-compat

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/apps/next-app/.next ./.next
COPY --from=base /app/apps/next-app/package.json ./

EXPOSE 3000

ENTRYPOINT ["npm", "run", "start"]